<a href="https://colab.research.google.com/github/gabrielalastra/PYTHON/blob/master/analysis_numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


criando um arranjo com 10 elementos e todos zero.

In [ ]:
matrix1 = np.array([0]*10)

In [ ]:
matrix1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

matrix 2x2 com numeros 1

In [ ]:
matrix2 = np.ones([2,2], dtype=np.int)

In [ ]:
matrix2

array([[1, 1],
       [1, 1]])

In [ ]:
#criando matrix 2 linhas e 2 colunas 
s=(2,2)

In [ ]:
np.ones(s)

array([[1., 1.],
       [1., 1.]])

In [ ]:
b = np.ones(s, dtype=np.int)

In [ ]:
b

array([[1, 1],
       [1, 1]])

In [ ]:
#matrix de 1 com 3x2 e numeros quebrados
matrix3 = np.ones([3,2], dtype=np.float)

In [ ]:
matrix3

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
#vetor de 5 a 10 indo de 2 tipo inteiro
x = np.arange(5,10,2, dtype=np.int)

In [ ]:
x

array([5, 7, 9])

In [ ]:
#transformar x em vetor de 1
np.ones_like(x)

array([1, 1, 1])

In [ ]:
#transformar x em vetor de 5
np.ones_like(x) *5

array([5, 5, 5])

In [ ]:
#criar y
y = np.array([[2,3], [6,3]], dtype=np.int)
y

array([[2, 3],
       [6, 3]])

In [ ]:
#transformar em matrix de 7
np.ones_like(y) *7

array([[7, 7],
       [7, 7]])

criando uma matrix 3x3 com 1 na diagonal e o resto zero

In [ ]:
A1=np.eye(3)
A1 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
A2 = np.identity((3), dtype=np.int)
A2

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
#matriz 2x4 com numeros randoms de 5 a 10 

A3 = np.random.randint(5,10, size=(2,4))
A3

array([[6, 5, 5, 8],
       [9, 6, 6, 6]])

In [ ]:
#matrix 3x3x3 com numeros randoms float

A4 = np.random.randn(3,3,3)
A4

array([[[-0.86639905,  0.86917958, -1.41599504],
        [ 1.68035103, -1.80689076,  1.45273833],
        [ 1.22003221,  0.47756285,  0.70053427]],

       [[ 0.39311926, -0.66473049, -0.76229491],
        [ 0.0777149 ,  1.35316785, -0.86414804],
        [ 0.5443623 , -2.24891306,  0.35583816]],

       [[-0.24631818,  0.69835108, -0.6000114 ],
        [-0.17187015,  0.05516954,  1.9413723 ],
        [-0.00253429,  1.09364675, -0.58812932]]])

In [ ]:
#converter uma lista python X em um vetor numpy
a = [1,2,2]
print(a, type(a), id(a))

[1, 2, 2] <class 'list'> 140648791596488


In [ ]:
b = np.array(a)
print(b, type(b), id(b))

#ID diferentes

[1 2 2] <class 'numpy.ndarray'> 140648791891200


In [ ]:
#vetor de 1 a 10 somente os numeros impares
c = np.arange(1,11,2)
c

array([1, 3, 5, 7, 9])

In [ ]:
#vetor de 10 a 1 em ordem decrescente
np.arange(1,11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
#matrix 3x3 indo de 0 a 8
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#mostrar a matrix 10x10 e o espaco em bytes que ocupa
z= np.zeros((10,10))
print("%d bytes" %(z.size*z.itemsize))
print(z)

800 bytes
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
x1 = np.array(['A','B','C','D','E'])
#mostre o primeiro elemento
print('o primeiro elemento de x1 é', x1[0])
#mostre o ultimio
print('o utlimo elemento de x1 é', x1[-1])

o primeiro elemento de x1 é A
o utlimo elemento de x1 é E


In [ ]:
#mostrar em ordem decrescente
x1[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [ ]:
#mostrar os elementos na posicao impar
x1[::2]

array(['A', 'C', 'E'], dtype='<U1')

In [ ]:
#matrix 4x4 com elementos de 0 a 3
x2 = np.arange(16).reshape(4,4)
print('a primeira linha de x2 é', x2[0])
print('a ultima linha de x2 é', x2[-1])
print('\n', x2)



In [ ]:
#criando a mesma matrix 4x4 mas comecando em 1
x3 = np.arange(1,17).reshape(4,4)
print('a primeira linha de x3 é', x3[0])
print('o primeiro elemento de x3 é', x3[0,0])

#os elementos do meio da matrix
print('\n', x3[1:-1,1:-1])

print('\n', x3)

a primeira linha de x3 é [1 2 3 4]
o primeiro elemento de x3 é 1

 [[ 6  7]
 [10 11]]

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
#os primeiros dois elementos x,y da matrix x3
x3[0:2,0:2]

array([[1, 2],
       [5, 6]])

manipulação de matrix

In [ ]:
#convertendo o tipo de dados em float
x4 = np.array(x3, np.float)
#invertendo os dados da matrix x3 e salvando em nova matrix
x4 = x3[::-1]
x4

array([[13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [ ]:
#ordenando novamente a matrix
x4.sort()
#alterando um valor da matrix, lembrando que conta 0
#se nao contasse a posicao 70 seria (3,4)
x4[2,3] = 70
x4[0,0] = 0
x4

array([[ 0,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 70],
       [13, 14, 15, 16]])

In [ ]:
#adicionar 5 em todos os elementos de x4
x4 +5 #pra salvar precisa x5 = x4+5 

array([[ 5,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 75],
       [18, 19, 20, 21]])

matrix boleanas (also called masks)

In [ ]:
X22 = np.array([
    [-1,   2,  3,  4],
    [5,   -6,  7,  8],
    [9,  10, -11, 12],
    [13, 14, 15, -16]
])
mask = X22 <= 0
mask

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [ ]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

#mostra os valores negativos
mask = X <= 0
print('Os valores negativos de X são \n', X[mask])

#mostra os elementos = 2 ou 10 
mask = (X == 2) | (X == 10)
print('os elementos iguais a 2 e 10 são \n', mask, '\n', X[mask], '\n')


Lógica de funções

In [ ]:
matrix4 = np.array([
                    [1, -2, 4, 5],
                    [3, 70, 60, 60],
                    [0, -4598, -12038, 323891] 
])

#return true if none of its elements is zero 
matrix4.all()


False

In [ ]:
#True if any of its elements is zero
matrix4.any()

True

In [ ]:
#soma dos elementos por coluna
matrix4.sum(axis=0)

array([     4,  -4530, -11974, 323956])

In [ ]:
#soma dos elementos por linha
matrix4.sum(axis=1)

array([     8,    193, 307255])

In [ ]:
#media por coluna e axis =1 eh por linha
matrix4.mean(axis=0)

array([ 1.33333333e+00, -1.51000000e+03, -3.99133333e+03,  1.07985333e+05])

In [ ]:
#valor maximo da matrix
matrix4.max()

323891