<a href="https://colab.research.google.com/github/gabrielalastra/PYTHON/blob/master/analysis_numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#usando numpy
import sys
import numpy as np

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
b = np.array([0, 0.5, 1, 1.5, 2])

In [ ]:
#retorna o elemento que esta na posicao
a[0], a[2], a[0:], a[1:3], a[1:-1], a[::2]

(1, 3, array([1, 2, 3, 4]), array([2, 3]), array([2, 3]), array([1, 3]))

In [ ]:
#o elemento -1 eh a ultima posicao
b, b[0], b[-1], b[-2], b[[0,2,-1]]

(array([0. , 0.5, 1. , 1.5, 2. ]), 0.0, 2.0, 1.5, array([0., 1., 2.]))

In [ ]:
#tipo de A e B
a.dtype


dtype('int64')

In [ ]:
b.dtype

dtype('float64')

In [ ]:
#convertendo em numero fracionado
np.array([a], dtype=np.float)

array([[1., 2., 3., 4.]])

In [ ]:
#convertendo float em numero com 8bytes de memoria de armazenagem
np.array([b], dtype=np.int8)

array([[0, 0, 1, 1, 2]], dtype=int8)

In [ ]:
c = np.array(['a','b','c'])

In [ ]:
c.dtype

dtype('<U1')

In [ ]:
A = np.array([
              [1,2,3],
              [4,5,6]
])

In [ ]:
#linhas e colunas
A.shape

(2, 3)

In [ ]:
#quantas dimensoes, no caso, vertical e horizontal
A.ndim

2

In [ ]:
#quantos elementos tem em A
A.size

6

In [ ]:
#criando um arranjo 3D como um cubo
B = np.array([
              [
                [12, 220, 22],
                [9,80,99]
              ],
              [
                [6,4,3],
                [3,2,1]
              ]
])

In [ ]:
B

array([[[ 12, 220,  22],
        [  9,  80,  99]],

       [[  6,   4,   3],
        [  3,   2,   1]]])

In [ ]:
B.shape #linhas, colunas e dimensoes

(2, 2, 3)

In [ ]:
B.ndim

3

In [ ]:
B.size

In [ ]:
#caso as dimensoes nao batam
C = np.array([
              [
               [12, 11, 10],
               [9,8,7],
              ],
              [
               [6,5,4]
              ]
])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


In [ ]:
#o tipo fica como objeto
C.dtype

dtype('O')

In [ ]:
C.shape

(2,)

In [ ]:
C.size

2

In [ ]:
A = np.array([
              #0 1 2
              [1,2,3], #0
              [4,5,6], #1
              [7,8,9] #2
])

In [ ]:
A[1]

In [ ]:
A[1][0]

In [ ]:
#A = [dimensao1, dimensao2, d3]
A[1,0]

In [ ]:
A[0:2]

In [ ]:
A.ndim

2

In [ ]:
A[:,:2]

array([[1, 2],
       [4, 5]])

In [ ]:
A[:2,:1]

array([[1],
       [4]])

In [ ]:
A[:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
#modificar a linha especificando
A[1] = np.array([10,100,1000])

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [ ]:
A[2] = 900 #geral

In [ ]:
A

array([[   1,    2,    3],
       [  10,  100, 1000],
       [ 900,  900,  900]])

In [ ]:
A.sum()

3816

In [ ]:
A.mean()

424.0

In [ ]:
#desvio padrao
A.std()

449.95431866900543

In [ ]:
#variancia
A.var()

202458.88888888888

In [ ]:
#somando a dimensao 0 que sao as colunas (Vert)
A.sum(axis=0)

array([ 911, 1002, 1903])

In [ ]:
A.sum(axis=1) #somando a dimensao 1 que sao as linhas (Horz)

array([   6, 1110, 2700])

In [ ]:
A.mean(axis=1) #axis refere a dimensao

array([  2., 370., 900.])

In [ ]:
A.std(axis=0)

array([421.68735127, 402.21718843, 448.28289679])

In [ ]:
#criando uma linha
D = np.arange(4)

In [ ]:
D

array([0, 1, 2, 3])

In [ ]:
#se colocar D + 100 vai mudar somente nessa cell
#com D += 100 muda a linha toda
#sem o np teria que fazer [i +100 for i in D]

D +=100

In [ ]:
D

array([100, 101, 102, 103])

In [ ]:
#fazendo uma matrix
a = np.array(np.mat('1,2;3,4'))

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
b = np.array(np.mat('10,10;10,10'))

In [ ]:
b

array([[10, 10],
       [10, 10]])

In [ ]:
a * b

array([[10, 20],
       [30, 40]])

In [ ]:
a2 = np.arange(4)

In [ ]:
a2

array([0, 1, 2, 3])

In [ ]:
#boolean array
a2[[True, False, False, True]]

array([0, 3])

In [ ]:
a2[[0,-1]]

array([0, 3])

In [ ]:
a2 >= 2

array([False, False,  True,  True])

In [ ]:
a2[a2 >= 2]

array([2, 3])

In [ ]:
a.mean()

2.5

In [ ]:
a2[a2 > a2.mean()]

array([2, 3])

In [ ]:
# o ~ marca a negacao
a2[~(a2 > a2.mean())]

array([0, 1])

In [ ]:
a2[(a2 == 0) | (a2 == 1)] # | or

array([0, 1])

In [ ]:
a2[(a2 <=2) & (a2 %2 == 0)] # & and

array([0, 2])

In [ ]:
#matriz booleana

B = np.random.randint(100, size=(3,3))

In [ ]:
B

array([[95, 18, 96],
       [63,  4, 74],
       [22, 79, 98]])

In [ ]:
B > 30 #quais elementos sao maiores que 30

array([[ True, False,  True],
       [ True, False,  True],
       [False,  True,  True]])

In [ ]:
B[B > 30] #escreva os elementos maiores que 30
# se quiser guardar var = B[B>30]

array([95, 96, 63, 74, 79, 98])

In [ ]:
B <= 30

array([[False,  True, False],
       [False,  True, False],
       [ True, False, False]])

In [ ]:

A2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:

B2 = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [ ]:
A2.dot(B2)

#produto escalar de dois arranjos
#[[1*6+2*4+3*2, 1*5+2*3+3*1],
# [4*6+5*4+6*2, 4*5+5*5+6*1],
# [7*6+8*4+9*2, 7*5+8*3+9*1]]

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
A2@B2 #tbm pode ser escrito assim

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
B2.T #inverte linhas em colunas

array([[6, 4, 2],
       [5, 3, 1]])

In [ ]:
B2.T @ A2

array([[36, 48, 60],
       [24, 33, 42]])

In [ ]:
#numero em python precisam de no minimo 28 bytes pra cada numero
sys.getsizeof(1)

28

In [ ]:
#com numpy o numero ocupa menos espaco da memoria ram, ocupando 8 bytes
np.dtype(int).itemsize

8

In [ ]:
#para ficar menos ainda
np.dtype(np.int8).itemsize

1

In [ ]:
np.dtype(float).itemsize

8

In [ ]:
#comparando a performance nao usando numpy
l = list(range(10000))

In [ ]:
%time sum([x **2 for x in l])

CPU times: user 3.86 ms, sys: 0 ns, total: 3.86 ms
Wall time: 6.2 ms


333283335000

In [ ]:
a = np.arange(10000)

In [ ]:
%time np.sum(a **2)

CPU times: user 870 µs, sys: 0 ns, total: 870 µs
Wall time: 867 µs


333283335000

# funções do **numpy**

In [ ]:
np.random.random(size=2)

array([0.20420097, 0.38301217])

In [ ]:
np.random.normal(size=2)

array([-0.74943901, -0.48391462])

In [ ]:
np.random.rand(2,4)

array([[0.88056361, 0.62177079, 0.36705603, 0.85081567],
       [0.6335869 , 0.1896769 , 0.92701604, 0.30900288]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(0,1,.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [ ]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
np.linspace(0,1,20,False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3,3), dtype=np.int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.empty((2,2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8,4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8,4,k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])