<a href="https://colab.research.google.com/github/gabrielalastra/PYTHON/blob/master/freecode_ex1_mean_var_std_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercício

Criar um vetor com 9 elementos e não aceita menos elementos

transformar em matriz 3x3

Criar uma função que calcula:
 - media aritmetica, 
 - variancia, 
 - desvio padrao, 
 - max e min

Imprimir um dicionario com os valores indicados para coluna, linhas e todos os elementos.

In [2]:
import numpy as np

In [26]:
x=[]

In [27]:
def createlist(x):
  i=0
  n=9
  while i<n:
    z = input('the element: ')
    if z.isnumeric():
      x.append(z)
      i+=1
    else:
      print('The list must containing 9 digits')
  return x

createlist(x)

the element: 1
the element: 2
the element: 33
the element: 43
the element: 2
the element: 12
the element: 3
the element: 12
the element: 43


['1', '2', '33', '43', '2', '12', '3', '12', '43']

In [28]:
x

['1', '2', '33', '43', '2', '12', '3', '12', '43']

In [29]:
x = np.array(x).reshape(3,3)
x

array([['1', '2', '33'],
       ['43', '2', '12'],
       ['3', '12', '43']], dtype='<U2')

In [6]:
#mean
mean_c = np.mean(x, axis=0)
mean_r = np.mean(x, axis=1)
mean_e = np.mean(x)

array([4., 5., 6.])

In [7]:
#variance and standard desviation
var_c = np.var(x, axis=0)
var_r = np.var(x, axis=1)
var_e = np.var(x)
std_c = np.std(x, axis=0)
std_r = np.std(x, axis=1)
std_e = np.std(x)


In [9]:
#max&min
max_c = np.max(x, axis=0)
max_r = np.max(x, axis=1)
max_e = np.max(x)
min_c = np.min(x, axis=0)
min_r = np.min(x, axis=1)
min_e = np.min(x)

In [12]:
#calculate
def calculate(x):
  dict={ 
      'mean' : [mean_r, mean_c, mean_e],
      'var' : [var_r, var_c, var_e],
      'std' : [std_r, std_c, std_e],
      'max' : [max_r, max_c, max_e],
      'min' : [min_r, min_c, min_e]
  }
  return dict

calculate(x)

{'max': [array([3, 6, 9]), array([7, 8, 9]), 9],
 'mean': [array([2., 5., 8.]), array([4., 5., 6.]), 5.0],
 'min': [array([1, 4, 7]), array([1, 2, 3]), 1],
 'std': [array([0.81649658, 0.81649658, 0.81649658]),
  array([2.44948974, 2.44948974, 2.44948974]),
  2.581988897471611],
 'var': [array([0.66666667, 0.66666667, 0.66666667]),
  array([6., 6., 6.]),
  6.666666666666667]}